### ISSUE TITLE
Is this operational?

### ISSUE THREAD

**Issue by pradyunsg** [ashwini0529/VIT-Student-API#3]
Hey there!

I was looking into trying to extract the VIT time table and other details programmatically. I see that you have done something similar here.

2 questions:
- What is the licensing of the contents of this repository?
- Could you take out some time and tell me how this is designed?

**Comment by shubhodeep9** [comment]
Hi @pradyunsg 
This repo was suspended, and the api was rebuilt in Golang
Here is the <a href="https://github.com/shubhodeep9/go-MyVIT">link</a>
